frame_id: map
initial_pose:
  x: 0.0
  y: 0.0
  yaw: 0.0

goals:
  desk:
    x: -0.683
    y: -0.044
    yaw: 1.777
  bed:
    x: -3.421
    y: 0.208
    yaw: 3.111
  kitchen:
    x: -3.150
    y: -3.106
    yaw: -1.419
