frame_id: map
initial_pose:
  x: 0.0
  y: 0.0
  yaw: 0.0

goals:
  desk:
    x: -0.378
    y: 0.035
    yaw: -2.579
  bed:
    x: 1.014
    y: -2.436
    yaw: -1.120
  kitchen:
    x: 3.802
    y: -0.851
    yaw: 0.623